services:
  - type: web
    name: tryon-app
    env: ruby
    buildCommand: bundle install && SECRET_KEY_BASE=dummy bundle exec rails assets:precompile && bundle exec rails db:create db:migrate
    startCommand: bundle exec rails server -e production -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
