development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || 'development_secret_key_base_that_is_at_least_thirty_characters_long' %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || 'test_secret_key_base_that_is_at_least_thirty_characters_long' %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

